# Generated by Django 5.2.15 on 2026-07-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('category_id', models.CharField(blank=True, max_length=32)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('item_specifics', models.JSONField(default=dict)),
                ('shipping', models.JSONField(default=dict)),
                ('listing_url', models.URLField(max_length=500)),
                ('listing_type', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('checkout_excluded', models.BooleanField(default=False)),
                ('ebay_started_at', models.DateTimeField(blank=True, null=True)),
                ('ebay_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=10)),
                ('indexed_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('deactivated_count', models.PositiveIntegerField(default=0)),
                ('seller_username', models.CharField(max_length=100)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('specifics', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('purchasable', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InventoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(choices=[('reserve', 'Checkout reservation'), ('release', 'Reservation release'), ('sale', 'Completed sale'), ('reconcile', 'Reconciliation')], max_length=12)),
                ('expected_quantity', models.PositiveIntegerField()),
                ('requested_quantity', models.PositiveIntegerField()),
                ('verified_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_operations', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_operations', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('position', models.PositiveSmallIntegerField()),
                ('variation_name', models.CharField(blank=True, max_length=120)),
                ('variation_value', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='unique_product_image_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'source_key'), name='unique_product_variant'),
        ),
    ]
