# Generated by Django 5.2.15 on 2026-07-12 21:36

import django.db.models.deletion
import django.db.models.expressions
import orders.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=orders.models.generate_order_reference, editable=False, max_length=13, unique=True)),
                ('status_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checkout_key', models.UUIDField(editable=False, unique=True)),
                ('checkout_fingerprint', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('payment_processing', 'Processing payment'), ('capture_pending', 'Confirming payment'), ('paid', 'Paid'), ('fulfilling', 'Fulfilling'), ('shipped', 'Shipped'), ('partially_refunded', 'Partially refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='awaiting_payment', max_length=24)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=300)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('shipping_line_1', models.CharField(max_length=300)),
                ('shipping_line_2', models.CharField(blank=True, max_length=300)),
                ('shipping_city', models.CharField(max_length=120)),
                ('shipping_region', models.CharField(max_length=120)),
                ('shipping_postal_code', models.CharField(max_length=32)),
                ('shipping_country_code', models.CharField(max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refunded_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paypal_status', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_nonnegative'), models.CheckConstraint(condition=models.Q(('shipping_total__gte', 0)), name='order_shipping_nonnegative'), models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('shipping_total')))), name='order_total_matches_parts'), models.CheckConstraint(condition=models.Q(('refunded_total__gte', 0), ('refunded_total__lte', models.F('total'))), name='order_refund_within_total')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('system', 'System'), ('paypal', 'PayPal'), ('admin', 'Administrator')], max_length=10)),
                ('event_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=32)),
                ('variation_sku', models.CharField(blank=True, max_length=100)),
                ('variation_title', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('committed', 'Committed'), ('released', 'Released')], default='reserved', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='orders.orderitem')),
            ],
            options={
                'ordering': ('expires_at',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=80)),
                ('tracking_number', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('label_created', 'Label created'), ('shipped', 'Shipped'), ('on_hold', 'On hold'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='shipped', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('paypal', 'PayPal')], default='manual', max_length=10)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('order', 'carrier', 'tracking_number'), name='unique_order_tracking_number'),
        ),
    ]
