# Generated by Django 5.2.15 on 2026-07-12 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('committing', 'Committing'), ('committed', 'Committed'), ('releasing', 'Releasing'), ('released', 'Released')], default='reserved', max_length=10),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_refund_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
        ),
    ]
