# Generated by Django 5.2.15 on 2026-07-13 10:33

from django.db import migrations, models


def consolidate_shipments(apps, schema_editor):
    Shipment = apps.get_model("orders", "Shipment")
    shipments = Shipment.objects.using(schema_editor.connection.alias)
    duplicates = list(
        shipments.values("order_id", "tracking_number")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        matching = shipments.filter(
            order_id=duplicate["order_id"],
            tracking_number=duplicate["tracking_number"],
        ).order_by("-updated_at", "-pk")
        keep = matching.first()
        matching.exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_inventoryreservation_status_refund'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipment',
            name='unique_order_tracking_number',
        ),
        migrations.RunPython(consolidate_shipments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('order', 'tracking_number'), name='unique_order_tracking_number'),
        ),
    ]
