# Generated by Django 5.2.15 on 2026-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_shipment_unique_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='provider_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
