# Generated by Django 5.2.15 on 2026-07-12 21:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('flat_shipping_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('checkout_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
